.\" Manpage for sp.
.\" Contact nbaltunian@gmail.com to correct errors or typos.
.TH sp 1 "18 Feb 2021" "0.1" "sp man page"
.SH NAME
sp \- Simple Port scanner
.SH SYNOPSIS
sp [hostname] [port[s]] [-u|--udp]
.SH DESCRIPTION
sp is an easy-to-use port scanner. It is a thin wrapper around `nc -z'.
.SH OPTIONS
sp accepts a UDP (-u|--udp) as a postfix option.
.SH SEE ALSO
nc(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Noah Altunian (nbaltunian@gmail.com)
